### ISSUE TITLE
Any plans to update the dependencies? "click<5.0" we are using already "click 6.7"

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [GoogleCloudPlatform/psq#39]
```
psq 0.6.0 has requirement click<5.0,>=4.0, but you'll have click 6.7 which is incompatible.
```

**Comment by Tachyon5** [comment]
I was wondering about this as well.

**Comment by theacodes** [comment]
A great recommendation, but I'm not actively maintaining this anymore as we've rolled most features into the upstream google-cloud-pubsub library. :)

**Comment by theacodes** [comment]
The plan is to update the tutorial to use pubsub directly, but we want to get that library to GA first. :)

**Comment by VelizarVESSELINOV** [comment]
I hope GA will be soon, to be honest, it is very difficult to follow what is GA at GCP, and also what it is the importance of GA, psq is Alpha (`Development Status :: 2`) on pypi and it still mandatory for GCP getting-started examples, even if the project is close to `Development Status :: 7` :)

**Comment by theacodes** [comment]
Indeed! Such is the way. We invent workarounds and gradually merge those
into full solutions.

When we wrote the getting-started tutorial, literally *nothing* we used
(other than the backing services for storage and datastore) was in GA. :)

**Comment by VelizarVESSELINOV** [comment]
@theacodes removing Flask from the equation, still have "troubles" to make these 2 GCP packages working together:
```bash
google-cloud-pubsub: 0.35.2 (current latest)
psq: 0.6.0 (current latest)
```

This is the error message using very minimalistic Pub/Sub queue creation and testing it with psqworker
```bash
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/psq/worker.py", line 37, in listen
    subscriber.future.result()

AttributeError: 'StreamingPullFuture' object has no attribute 'future'
```
psq dependency defined to pubsub is: 
```google-cloud-pubsub>=0.29.0```

The code is working with OK with google-cloud-pubsub 0.29, but KO with the latest google-cloud-pubsub: 0.35.2

It is a not funny game to build apps on GCP with all the mutually incompatible packages, especially when you are trying to do professional solutions. IMHO psq need an urgent update to catch with the other google packages and flask (`click` recent version) or switch to alternative solution like pq/celery.

**Comment by VelizarVESSELINOV** [comment]
@theacodes thank you very much for the fix, much appreciated.

I hope one-day pubsub will cover all the needed functionalities and psq and psqworker will disappear, in the transition time is very helpful to have working solutions between the maturing pubsub and the obsolescence psq.
